version: "2"
services:
  selenium-hub:
    restart: always
    image: selenium/hub
    container_name: "selenium-hub"
    ports:
      - "4444:4444"

  chrome:
    restart: always
    image: selenium/node-chrome-debug
    container_name: "chrome"
    environment:
      HUB_HOST: selenium-hub
    ports:
      - "5901:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
